config/routes.rb
Rails.application.routes.draw do
  resources :pokemons

  root 'pokemons#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'pp'
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	def index
		response = HTTParty.get('http://pokeapi.co/api/v2/pokemon')
		response = JSON.parse(response.body)
		pp response
		@pokemons = response["results"]
	end

	def show
		# puts params[:id]
		response = HTTParty.get('http://pokeapi.co/api/v2/pokemon/' + params[:id])
		pp JSON.parse(response.body)
		@pokemon = JSON.parse(response.body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<h1>Dope Boy Fresh - Add banner</h1>
</header>
<nav>
	<ul>
		<li><%= link_to("Home", root_path) %></li>
		<li><%= link_to("Pokemon", pokemons_path) %></li>
	</ul>
</nav>

<%= yield %>

</body>
</html>

app/views/pokemons/index.html.erb
<div class="pokemon-container">
<% @pokemons.each do |pokemon| %>
	<div class="pokemon"> <%= link_to(pokemon["name"].capitalize, pokemon_path(pokemon["name"])) %>
		</div>
<% end %>
</div>

app/views/pokemons/show.html.erb
<div>
<%= image_tag(@pokemon["sprites"]["front_default"]) %></br>
<%= @pokemon["name"].capitalize %></br>
Weight: <%= @pokemon["weight"] %></br>
</div>

</div>
<%= link_to_if(@pokemon["id"] > 1, "Previous", pokemon_path(@pokemon["id"] - 1)) %>
<%= link_to_if(@pokemon["id"] < 721, "Next", pokemon_path(@pokemon["id"] + 1)) %>
</div>